apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - image: artifactory.i.mct360.com/artifactory/docker-ma/app1:1.0
        name: app1
        ports:
        - containerPort: 80
