replicaCount: 1

image:
  repository: "artifactory.i.mct360.com/docker-ma"
  name: app1
  tag: 
  pullPolicy: Always

nameOverride: app1
fullnameOverride: app1

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
  tlsenabled: true
